# Generated by Django 3.0.6 on 2020-07-12 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SideChainBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_size', models.IntegerField()),
                ('block_version', models.CharField(max_length=20)),
                ('project_id', models.IntegerField()),
                ('contributor_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_file', models.CharField(max_length=200)),
                ('previous_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.SideChainBlock')),
            ],
        ),
        migrations.CreateModel(
            name='SideChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.SideChainBlock')),
            ],
        ),
        migrations.CreateModel(
            name='PublicChainBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100)),
                ('block_version', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.PublicChainBlock')),
            ],
        ),
    ]
