# Generated by Django 3.0.6 on 2020-07-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidechain',
            name='block',
        ),
    ]
