# Generated by Django 3.0.6 on 2020-07-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_remove_sidechain_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidechainblock',
            name='side_chain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blockchain.SideChain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sidechainblock',
            name='previous_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.SideChainBlock'),
        ),
    ]
