# Generated by Django 3.0.6 on 2020-07-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20200713_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidechainblock',
            name='previous_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.SideChainBlock'),
        ),
    ]
