# Generated by Django 3.0.6 on 2020-07-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_auto_20200714_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchainblock',
            name='previous_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.PublicChainBlock'),
        ),
    ]
